baseURL = "https://docs.chat.academiccloud.de/"
languageCode = "de-DE"
DefaultContentLanguage = "de"
title = "Matrix Dokumentation"
theme = "hugo-theme-relearn"

[params]
  themeVariant = "ac"
  disableNextPrev = true
  disableShortcutsTitle = false
  showVisitedLinks = false
  disableBreadcrumb = false
  disableMermaid = false

[outputs]
  home = [ "HTML", "RSS", "SEARCH"]

# No newline (<br/>) unless unsafe is enabled
# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[languages]
  [languages.de]
    title = "Matrix Dokumentation"
    weight = 1
    languageName = "Deutsch"